DROP TABLE user
IF EXISTS;
CREATE TABLE user (
  user_id  INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (
  START WITH 100 ),
  username VARCHAR(50)  NOT NULL,
  email    VARCHAR(50)  NOT NULL,
  pw       VARCHAR(255) NOT NULL
);

DROP TABLE application
IF EXISTS;
CREATE TABLE application (
  application_id     INTEGER,
  application_status VARCHAR(160)
);

DROP TABLE message
IF EXISTS;
CREATE TABLE message (
  message_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (
  START WITH 100 ),
  author_id  INTEGER      NOT NULL,
  job        VARCHAR(50)  NOT NULL,
  text       VARCHAR(160) NOT NULL,
  pub_date   TIMESTAMP
);